name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Todo App
      run: |
        ls -la ./todohtml
        docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app:latest ./todohtml
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app:latest

    - name: Build and push Personal Website
      run: |
        ls -la ./html
        docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:latest ./html
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:latest

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST_SERVER }}
        USERNAME: ${{ secrets.HOST_USER_NAME }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          docker pull $DOCKER_USERNAME/todo-app:latest &&
          docker pull $DOCKER_USERNAME/personal-website:latest &&
          docker stop todo-app || true &&
          docker rm todo-app || true &&
          docker stop personal-website || true &&
          docker rm personal-website || true &&
          docker run -d -p 8085:80 --name todo-app $DOCKER_USERNAME/todo-app:latest &&
          docker run -d -p 8081:80 --name personal-website $DOCKER_USERNAME/personal-website:latest
        "
